"""integrations/report_pdf.py — generate a styled meeting-report PDF (F4 output).

Bridges the team's Notebook 3 (reportlab) into the bot so JARVIS can generate a
readable, branded PDF report from structured meeting data and post it to Discord.

The summary dict produced by integrations/voice.py already carries:
  {title?, summary, decisions[], tasks[{task, assignee, deadline}]}
We normalise to that shape (title defaults to the source filename) and render.

Dependencies: reportlab (see requirements.txt). If it is not installed, the
module degrades gracefully instead of crashing the bot.
"""
import logging
import os
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib.enums import TA_LEFT, TA_CENTER
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        HRFlowable, ListFlowable, ListItem,
    )
    _HAS_REPORTLAB = True
except Exception:
    _HAS_REPORTLAB = False

logger = logging.getLogger("jarvis.report_pdf")

REQUIRED_KEYS = {"summary", "decisions", "tasks"}

_COLOR_PRIMARY = "#1F3A5F"
_COLOR_SECONDARY = "#3E7CB1"
_COLOR_ACCENT = "#E8A33D"
_ORG = "JARVIS Agentic Team Assistant"


def _styles():
    base = getSampleStyleSheet()
    return {
        "ReportTitle": ParagraphStyle("ReportTitle", parent=base["Title"],
                                      fontName="Helvetica-Bold", fontSize=20,
                                      textColor=colors.HexColor(_COLOR_PRIMARY),
                                      alignment=TA_LEFT, spaceAfter=4),
        "SubTitle": ParagraphStyle("SubTitle", parent=base["Normal"],
                                   fontSize=10, textColor=colors.HexColor(_COLOR_SECONDARY),
                                   alignment=TA_LEFT, spaceAfter=12),
        "SectionHeading": ParagraphStyle("SectionHeading", parent=base["Heading2"],
                                        fontName="Helvetica-Bold", fontSize=14,
                                        textColor=colors.HexColor(_COLOR_PRIMARY),
                                        spaceBefore=14, spaceAfter=8),
        "Body": ParagraphStyle("Body", parent=base["Normal"], fontSize=10.5,
                               textColor=colors.HexColor("#212121"), leading=15),
        "BulletBody": ParagraphStyle("BulletBody", parent=base["Normal"], fontSize=10.5,
                                     textColor=colors.HexColor("#212121"), leading=14),
        "TableCell": ParagraphStyle("TableCell", parent=base["Normal"], fontSize=9.5,
                                    textColor=colors.HexColor("#212121"), leading=12),
        "TableHeaderCell": ParagraphStyle("TableHeaderCell", parent=base["Normal"],
                                          fontName="Helvetica-Bold", fontSize=10,
                                          textColor=colors.white, alignment=TA_CENTER),
    }


def _normalize(data: Dict[str, Any]) -> Dict[str, Any]:
    """Guarantee {title, summary, decisions[], tasks[{task,assignee,deadline}]}."""
    return {
        "title": str(data.get("title") or data.get("source") or "Meeting Report"),
        "summary": str(data.get("summary") or ""),
        "decisions": [str(d) for d in (data.get("decisions") or [])],
        "tasks": data.get("tasks") or [],
    }


def generate_report_pdf(data: Dict[str, Any], output_path: Optional[str] = None) -> str:
    """Render a styled PDF meeting report. Returns the output file path.

    Falls back to a plain-text note if reportlab is unavailable so the bot always
    produces something rather than crashing.
    """
    if not _HAS_REPORTLAB:
        logger.warning("reportlab not installed — falling back to text file.")
        return _fallback_text(data, output_path)

    data = _normalize(data)
    out = output_path or os.path.join(tempfile.gettempdir(),
                                      f"meeting_{datetime.now():%Y%m%d_%H%M%S}.pdf")
    sty = _styles()
    generated_on = datetime.now().strftime("%B %d, %Y at %H:%M")

    story = []
    story.append(Paragraph(data["title"], sty["ReportTitle"]))
    story.append(Paragraph(f"Generated by {_ORG} • {generated_on}", sty["SubTitle"]))
    story.append(HRFlowable(width="100%", thickness=2,
                            color=colors.HexColor(_COLOR_ACCENT), spaceAfter=14))

    story.append(Paragraph("Executive Summary", sty["SectionHeading"]))
    story.append(Paragraph(data["summary"] or "No summary.", sty["Body"]))
    story.append(Spacer(1, 6))

    story.append(Paragraph("Key Decisions", sty["SectionHeading"]))
    decisions = data["decisions"]
    if decisions:
        items = [ListItem(Paragraph(d, sty["BulletBody"]), bulletColor=colors.HexColor(_COLOR_SECONDARY))
                 for d in decisions]
        story.append(ListFlowable(items, bulletType="bullet", start="circle", leftIndent=14))
    else:
        story.append(Paragraph("No decisions were recorded.", sty["Body"]))
    story.append(Spacer(1, 6))

    story.append(Paragraph("Action Items", sty["SectionHeading"]))
    tasks = data["tasks"]
    if tasks:
        rows = [[Paragraph("Task", sty["TableHeaderCell"]),
                 Paragraph("Assignee", sty["TableHeaderCell"]),
                 Paragraph("Deadline", sty["TableHeaderCell"])]]
        for t in tasks:
            rows.append([Paragraph(t.get("task", "-"), sty["TableCell"]),
                         Paragraph(t.get("assignee", "Unassigned"), sty["TableCell"]),
                         Paragraph(t.get("deadline", "Not specified"), sty["TableCell"])])
        tbl = Table(rows, colWidths=[8.5 * cm, 4 * cm, 4 * cm], repeatRows=1)
        cmds = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(_COLOR_PRIMARY)),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ALIGN", (0, 0), (-1, 0), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D0D5DD")),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]
        for r in range(1, len(rows)):
            if r % 2 == 0:
                cmds.append(("BACKGROUND", (0, r), (-1, r), colors.HexColor("#F2F5F9")))
        tbl.setStyle(TableStyle(cmds))
        story.append(tbl)
    else:
        story.append(Paragraph("No action items were recorded.", sty["Body"]))

    def _footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica-Oblique", 8)
        canvas.setFillColor(colors.HexColor("#8A8A8A"))
        canvas.drawCentredString(doc.pagesize[0] / 2.0, 1.2 * cm,
                                 f"{_ORG}  |  Page {doc.page}")
        canvas.restoreState()

    doc = SimpleDocTemplate(out, pagesize=A4,
                            leftMargin=2 * cm, rightMargin=2 * cm,
                            topMargin=2 * cm, bottomMargin=2 * cm,
                            title=data["title"], author=_ORG)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    logger.info("[report_pdf] generated %s", out)
    return out


def _fallback_text(data: Dict[str, Any], output_path: Optional[str]) -> str:
    out = output_path or os.path.join(tempfile.gettempdir(),
                                      f"meeting_{datetime.now():%Y%m%d_%H%M%S}.txt")
    d = _normalize(data)
    lines = [f"{d['title']}\n", f"Generated by {_ORG}\n", "\nExecutive Summary\n", d["summary"], ""]
    if d["decisions"]:
        lines += ["\nKey Decisions"] + [f"  • {x}" for x in d["decisions"]]
    if d["tasks"]:
        lines += ["\nAction Items"] + [f"  • {t.get('task')} — {t.get('assignee')} · {t.get('deadline')}"
                                       for t in d["tasks"]]
    Path(out).write_text("\n".join(lines), encoding="utf-8")
    return out
